# Permalinks
#
permalink:           /:categories/:title

# Setup
title:               Very Thorough
tagline:             "Jessica Parsons's Home on the Web"
description:         ''
url:                 http://verythorough.github.io
baseurl:             ''

# About/contact
author:
  name:              Jessica Parsons
  url:               http://verythorough.github.io
  email:             verythorough@gmail.com

# Jekyll configuration
sass:
    sass_dir: _sass
    style: :compressed
kramdown:
  auto_ids: false
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
exclude: ["notestoself", "Gemfile", "Gemfile.lock", "LICENSE.md", "README.md"]

# Defaults
defaults:
  -
    scope:
      path: "journal"
    values:
      layout: "post"
  -
    scope:
      path: "projects"
    values:
      layout: "project"
      img_type: "jpg"

# Prose
prose:
  siteurl: 'https://verythorough.github.io'
  media: 'images'
  metadata:
    journal/_posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: "false"
