# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Very Thorough
tagline:             'Portfolio and resume for Jessica Parsons'
description:         ''
url:                 http://verythorough.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jessica Parsons
  url:               http://verythorough.github.io
  email:             verythorough@gmail.com

# Jekyll configuration
sass:
    sass_dir: _sass
    style: compressed
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  
# Custom vars
version:             1.0.0
